# controller_manager_ns: /jaco
controller_list:
  - name: jaco_arm_controller
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: true
    joints:
      - jaco_joint_1
      - jaco_joint_2
      - jaco_joint_3
      - jaco_joint_4
      - jaco_joint_5
      - jaco_joint_6
  - name: jaco_gripper_controller
    type: FollowJointTrajectory
    action_ns: follow_joint_trajectory
    default: false
    joints:
      - jaco_joint_finger_1
      - jaco_joint_finger_2
      - jaco_joint_finger_3
      - jaco_joint_finger_tip_1
      - jaco_joint_finger_tip_2
      - jaco_joint_finger_tip_3